; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
	;I2Cdev
	;MPU6050
	;WiFi
	;ESP Async WebServer
    ;me-no-dev/AsyncTCP @ ^1.1.1
	;nkolban/ESP32 BLE Arduino @ ^1.0.1
	;h2zero/NimBLE-Arduino

; uncomment the specific test flag for the feature you want to test
;build_flags = -DRUN_GYRO_TEST
;build_flags = -DRUN_SENSORS_TEST
;build_flags = -DRUN_LINE_SENSOR
;build_flags = -DRUN_WIFI_SENSORS_TEST
;build_flags = -DRUN_DRIVER_TEST
;build_flags = -DRUN_LS_SENSOR_TEST
;build_flags = -DRUN_TASK_TEST
;build_flags = -DRUN_MOVEMENT_SENSOR_CALIBRATION
;build_flags = -DFAST_ENEMY
;build_flags = -DCANCEL_TURNS

build_flags = ;FIGHT
	-DESTADOS_ORDEN
	-DMBARETECH_2
	-DRUN_LINE_SENSOR
	-DRUN_TASK_TEST
	-DFAST_ENEMY
	-DCANCEL_TURNS
	-DFORWARDON
	;-DDEBUG

;build_flags = ;DRIVER TEST
;	-DMBARETECH_2
;	-DRUN_LINE_SENSOR
;	-DRUN_DRIVER_TEST
;	-DDEBUG

;build_flags = ;MOVEMENT TESTS
	;-DMBARETECH_2
	;-DRUN_MOVEMENTS_TEST
	;-DRUN_LINE_SENSOR
	;-DCANCEL_TURNS
	;-DDEBUG
	

;build_flags = ;SENSORS TEST
	;-DMBARETECH_2
	;-DRUN_LINE_SENSOR
	;-DRUN_SENSORS_TEST
	;-DDEBUG

