/* Pruebas del contrato real, catálogos dinámicos y exportación sin tipos duplicados. */
const assert=require('node:assert/strict'), fs=require('node:fs'), path=require('node:path');
const C=require('./core.js'), root=path.resolve(__dirname,'../..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const types=read('include/fsm/FSMRecipeTypes.h'), defs=read('include/fsm/FSMDefinitions.h');
const api=C.loadAPI(types,defs);
const recipe=C.importRecipe(api,read('include/fsm/recipes/fsm_recipe_turn_calibration.h'),'fsm_recipe_turn_calibration.h');
// La receta TEST anterior debe conservar ciclo, intervalos y comandos tras migrar.
const cycle=C.importRecipe(api,read('include/fsm/recipes/fsm_recipe_test.h'),'fsm_recipe_test.h');
assert.deepEqual(cycle.states.map(state=>state.id),['IDLE','MOTOR_SEQUENCE','MOTOR_SEQUENCE_1']);
assert.deepEqual(cycle.states.map(state=>C.number(api,state.transitions[0].timer)),[5000,2500,2500]);
assert.deepEqual(cycle.states.map(state=>C.number(api,state.left)),[0,100,-100]);
assert.deepEqual(cycle.states.map(state=>state.transitions[0].target),['MOTOR_SEQUENCE','MOTOR_SEQUENCE_1','MOTOR_SEQUENCE']);
assert.equal(C.importRecipe(api,C.emit(api,cycle),cycle.file).states.length,3);
assert.equal(cycle.parameters.length,2);
assert.equal(C.importRecipe(api,C.emit(api,cycle),cycle.file).states[1].leftParameter,1);
assert.equal(recipe.states[1].steps.length,3);
const output=C.emit(api,recipe);
assert(!/enum class|struct\s+\w/.test(output));
assert.equal(C.emit(api,C.importRecipe(api,output,recipe.file)),output);
assert.deepEqual(recipe.parameters.map(p=>p.key),['left_turn_duration','right_turn_duration']);
assert.equal(recipe.states[1].steps[0].transitions[0].timerParameter,1);
assert.equal(recipe.states[1].steps[2].transitions[0].timerParameter,2);
const roundtrip=C.importRecipe(api,output,recipe.file);
assert.deepEqual(roundtrip.parameters,recipe.parameters);
assert.equal(roundtrip.states[1].steps[0].transitions[0].timerParameter,1);
const readOnly=structuredClone(recipe);readOnly.parameters[0].writable=false;
assert.equal(C.importRecipe(api,C.emit(api,readOnly),recipe.file).parameters[0].writable,false);
const duplicateParameter=structuredClone(recipe);
duplicateParameter.parameters[1].key=duplicateParameter.parameters[0].key;
assert(C.validate(api,duplicateParameter).some(error=>/Clave de parámetro/.test(error)));
const missingParameter=structuredClone(recipe);
missingParameter.states[1].steps[0].transitions[0].timerParameter=99;
assert(C.validate(api,missingParameter).some(error=>/referencia de parámetro/.test(error)));
assert.throws(()=>C.loadAPI(types.replace('uint8_t termCount','uint16_t termCount'),defs),/incompatible/);
assert.throws(()=>C.loadAPI(types.replace('struct MachineRecipe','struct OtherRecipe'),defs),/incompatible/);
assert.throws(()=>C.loadAPI(types,defs.replace('SCHEMA_VERSION = 2','SCHEMA_VERSION = 1')),/incompatible/);
const changed=defs.replace('MOTOR_SEQUENCE_2, COUNT','MOTOR_SEQUENCE_2, SEARCH, COUNT').replace(/    COUNT\r?\n/,'    CUSTOM_SENSOR, COUNT\n');
const dynamic=C.loadAPI(types,changed);assert(dynamic.states.includes('SEARCH'));assert(dynamic.conditions.includes('CUSTOM_SENSOR'));
const reordered=C.loadAPI(types.replace('int8_t left_pct;','int8_t temporary;').replace('int8_t right_pct;','int8_t left_pct;').replace('int8_t temporary;','int8_t right_pct;'),defs);
const asymmetric=C.freshRecipe(reordered,'Orden');asymmetric.states[0].left=12;asymmetric.states[0].right=-34;
assert(C.emit(reordered,asymmetric).includes('{-34, 12, 0, 0}'));
assert.equal(C.importRecipe(reordered,C.emit(reordered,asymmetric),asymmetric.file).states[0].left,'12');
assert.equal(C.normalize('Motor Test 2').file,'fsm_recipe_motor_test_2.h');
assert.equal(C.normalize('Ángulo 2').namespace,'fsm_recipe_angulo_2');
const fresh=C.freshRecipe(api,'EDITOR_TEST');
assert.equal(C.validate(api,fresh).length,0);
assert.equal(C.importRecipe(api,C.emit(api,C.freshRecipe(api,'Prueba // texto')),fresh.file).name,'Prueba // texto');
function invalid(mutate,pattern){const r=structuredClone(recipe);mutate(r);assert(C.validate(api,r).some(e=>pattern.test(e)));assert.throws(()=>C.emit(api,r),/No se puede generar/);}
invalid(r=>r.initialState='MISSING',/inicial/);
invalid(r=>r.states[1].id=r.states[0].id,/único/);
invalid(r=>r.states[0].id='MISSING',/no existe/);
invalid(r=>r.states[0].motion='MISSING',/MotionId/);
invalid(r=>r.states[0].left=101,/rango/);
invalid(r=>r.states[0].transitions[0].target='MISSING',/destino/);
invalid(r=>r.states[1].transitions[0].terms=['MISSING'],/ConditionId/);
invalid(r=>r.states[1].transitions[0].operators=[],/operadores/);
invalid(r=>r.states[1].steps=[],/pasos/);
invalid(r=>r.states[1].steps[0].transitions[0].target=50,/destino/);
invalid(r=>r.states[1].steps[0].transitions[0].type='COMPLETION',/COMPLETION/);
invalid(r=>r.states[1].transitions=r.states[1].transitions.filter(t=>t.type!=='COMPLETION'),/retención/);
invalid(r=>r.name='',/nombre/);
assert.throws(()=>C.importRecipe(api,'enum class MacroId { X };','bad.h'),/incompatible/);
const config=read('include/buildConfig.h'), selector=read('include/fsm/fsm_recipe_select.h');
const patched=C.patchConfig(config,{ENABLE_MOTORS:0},fresh.macro);
assert(patched.includes('#define '+fresh.macro));
assert(patched.includes('#define '+fresh.macro));
const entries=C.selections(selector).filter(e=>e.macro!==fresh.macro);entries.push(fresh);
const selected=C.patchSelection(selector+'\n// Texto ajeno que debe conservarse.\n',entries);
assert(selected.endsWith('// Texto ajeno que debe conservarse.\n'));
assert(C.selections(selected).some(e=>e.file===fresh.file));
assert.throws(()=>C.patchSelection(selector.replace('namespace active_fsm_recipe =','int extra;\nnamespace active_fsm_recipe ='),entries),/adicional|incompatible/);
// Archivos de prueba para compilar con el validador C++ real.
const build=path.join(root,'.pio/editor-tests');fs.mkdirSync(build,{recursive:true});
for(const [file,source]of [['roundtrip.h',output],['fresh.h',C.emit(api,fresh)]])fs.writeFileSync(path.join(build,file),source.replace('../FSMRecipeTypes.h','fsm/FSMRecipeTypes.h'));
fs.writeFileSync(path.join(build,'validate.cpp'),'#include <cassert>\n#include "fsm/StateMachine.h"\n#include "roundtrip.h"\n#include "fresh.h"\nint main(){assert(!fsm::validateRecipe(fsm_recipe_turn_calibration::MACHINE));assert(!fsm::validateRecipe(fsm_recipe_editor_test::MACHINE));}\n');
console.log('Correcto: API dinámico, importación/exportación, validaciones y cambios acotados de configuración.');

